application: 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: wsgi.application

libraries:
- name: pycrypto
  version: '2.3'
- name: webob
  version: '1.1.1'